"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _earn_prompt_grid from './earn-prompt-grid.bones.json'
import _earn_skills_grid from './earn-skills-grid.bones.json'
import _earn_llm_grid from './earn-llm-grid.bones.json'
import _earn_token_grid from './earn-token-grid.bones.json'
import _earn_yield_panel from './earn-yield-panel.bones.json'
import _earn_page from './earn-page.bones.json'
import _earn_token_detail from './earn-token-detail.bones.json'
import _earn_yield_detail from './earn-yield-detail.bones.json'
import _playground_catalog from './playground-catalog.bones.json'
import _playground_catalog_share from './playground-catalog-share.bones.json'
import _marketplace_api_detail from './marketplace-api-detail.bones.json'
import _assets_table from './assets-table.bones.json'
import _asset_intelligence from './asset-intelligence.bones.json'
import _asset_detail from './asset-detail.bones.json'
import _pumpfun_list from './pumpfun-list.bones.json'
import _pumpfun_leaderboard from './pumpfun-leaderboard.bones.json'
import _pumpfun_analysis from './pumpfun-analysis.bones.json'
import _labs_wallet_list from './labs-wallet-list.bones.json'
import _labs_call_log from './labs-call-log.bones.json'
import _labs_auto_call from './labs-auto-call.bones.json'
import _labs_deposit_hub from './labs-deposit-hub.bones.json'
import _labs_endpoints from './labs-endpoints.bones.json'
import _llm_model_selector from './llm-model-selector.bones.json'
import _invest_page from './invest-page.bones.json'
import _spend_page from './spend-page.bones.json'
import _spend_preview from './spend-preview.bones.json'
import _grow_analysis from './grow-analysis.bones.json'
import _lp_pools from './lp-pools.bones.json'
import _treasury_panel from './treasury-panel.bones.json'
import _treasury_spend from './treasury-spend.bones.json'
import _organize_summary from './organize-summary.bones.json'
import _organize_table from './organize-table.bones.json'
import _swap_details from './swap-details.bones.json'
import _swap_token_list from './swap-token-list.bones.json'
import _swap_market from './swap-market.bones.json'
import _swap_x_posts from './swap-x-posts.bones.json'
import _btc_hero from './btc-hero.bones.json'
import _btc_stats from './btc-stats.bones.json'
import _btc_exchange from './btc-exchange.bones.json'
import _btc_chart from './btc-chart.bones.json'
import _staking_stats from './staking-stats.bones.json'
import _staking_locks from './staking-locks.bones.json'
import _chat_sidebar from './chat-sidebar.bones.json'
import _growth_metrics from './growth-metrics.bones.json'
import _articles_list from './articles-list.bones.json'
import _agent_setup_sections from './agent-setup-sections.bones.json'
import _overview_chart from './overview-chart.bones.json'
import _overview_stat from './overview-stat.bones.json'
import _experiment_leaderboard from './experiment-leaderboard.bones.json'
import _post_studio from './post-studio.bones.json'
import _pillar_card from './pillar-card.bones.json'
import _pumpfun_price_chart from './pumpfun-price-chart.bones.json'

configureBoneyard({"color":"hsl(0 0% 96% / 0.5)","darkColor":"hsl(220 10% 11% / 0.5)","animate":"shimmer","shimmerColor":"hsl(0 0% 6% / 0.07)","darkShimmerColor":"hsl(210 20% 98% / 0.07)","speed":"1.8s"})

registerBones({
  "earn-prompt-grid": _earn_prompt_grid,
  "earn-skills-grid": _earn_skills_grid,
  "earn-llm-grid": _earn_llm_grid,
  "earn-token-grid": _earn_token_grid,
  "earn-yield-panel": _earn_yield_panel,
  "earn-page": _earn_page,
  "earn-token-detail": _earn_token_detail,
  "earn-yield-detail": _earn_yield_detail,
  "playground-catalog": _playground_catalog,
  "playground-catalog-share": _playground_catalog_share,
  "marketplace-api-detail": _marketplace_api_detail,
  "assets-table": _assets_table,
  "asset-intelligence": _asset_intelligence,
  "asset-detail": _asset_detail,
  "pumpfun-list": _pumpfun_list,
  "pumpfun-leaderboard": _pumpfun_leaderboard,
  "pumpfun-analysis": _pumpfun_analysis,
  "labs-wallet-list": _labs_wallet_list,
  "labs-call-log": _labs_call_log,
  "labs-auto-call": _labs_auto_call,
  "labs-deposit-hub": _labs_deposit_hub,
  "labs-endpoints": _labs_endpoints,
  "llm-model-selector": _llm_model_selector,
  "invest-page": _invest_page,
  "spend-page": _spend_page,
  "spend-preview": _spend_preview,
  "grow-analysis": _grow_analysis,
  "lp-pools": _lp_pools,
  "treasury-panel": _treasury_panel,
  "treasury-spend": _treasury_spend,
  "organize-summary": _organize_summary,
  "organize-table": _organize_table,
  "swap-details": _swap_details,
  "swap-token-list": _swap_token_list,
  "swap-market": _swap_market,
  "swap-x-posts": _swap_x_posts,
  "btc-hero": _btc_hero,
  "btc-stats": _btc_stats,
  "btc-exchange": _btc_exchange,
  "btc-chart": _btc_chart,
  "staking-stats": _staking_stats,
  "staking-locks": _staking_locks,
  "chat-sidebar": _chat_sidebar,
  "growth-metrics": _growth_metrics,
  "articles-list": _articles_list,
  "agent-setup-sections": _agent_setup_sections,
  "overview-chart": _overview_chart,
  "overview-stat": _overview_stat,
  "experiment-leaderboard": _experiment_leaderboard,
  "post-studio": _post_studio,
  "pillar-card": _pillar_card,
  "pumpfun-price-chart": _pumpfun_price_chart,
})
