/**
 * Syra x402 playground catalog (offline fallback + tests).
 * AUTO-GENERATED by scripts/sync-x402-playground-catalog.mjs — do not edit manually.
 */
import type { HttpMethod } from "@/types/api";
import type { RequestParam } from "@/types/api";

export const X402_PLAYGROUND_GENERATED_AT = "2026-07-15T03:52:48.712Z";

export interface X402PlaygroundResourceTemplate {
  segment: string;
  id: string;
  label: string;
  method: HttpMethod;
  params: RequestParam[];
  body?: string;
  catalogMeta?: {
    segment: string;
    name: string;
    summary: string;
    description?: string;
    priceUsd?: string;
    category?: string;
  };
}

export const X402_PLAYGROUND_RESOURCE_TEMPLATES: X402PlaygroundResourceTemplate[] = [
  {
    "segment": "brain",
    "id": "x402-brain",
    "label": "Syra Brain: Single-question crypto AI with automatic tool selection",
    "method": "GET",
    "params": [
      {
        "key": "question",
        "value": "",
        "enabled": true,
        "description": "Natural language question."
      }
    ],
    "catalogMeta": {
      "segment": "brain",
      "name": "Syra Brain",
      "summary": "Single-question crypto AI with automatic tool selection",
      "description": "Answers one natural-language crypto question by selecting and running Syra tools (news, signals, on-chain reads) server-side. Use when an a…",
      "priceUsd": "0.08",
      "category": "ai"
    }
  },
  {
    "segment": "news",
    "id": "x402-news",
    "label": "Crypto News: Latest crypto news headlines and summaries",
    "method": "GET",
    "params": [
      {
        "key": "ticker",
        "value": "general",
        "enabled": true,
        "description": "Ticker symbol or general for broad feed."
      }
    ],
    "catalogMeta": {
      "segment": "news",
      "name": "Crypto News",
      "summary": "Latest crypto news headlines and summaries",
      "description": "Curated crypto news articles with titles, sources, and URLs. Use when an agent needs recent headlines for a token, sector, or the whole mar…",
      "priceUsd": "0.005",
      "category": "news"
    }
  },
  {
    "segment": "signal",
    "id": "x402-signal",
    "label": "Trading Signal: AI trading signal from CEX OHLCV technical analysis",
    "method": "GET",
    "params": [
      {
        "key": "token",
        "value": "bitcoin",
        "enabled": true,
        "description": "Asset name for signal routing (e.g. bitcoin, solana)."
      },
      {
        "key": "source",
        "value": "",
        "enabled": false,
        "description": "Data source. Default: binance. CEX: binance, coinbase, coingecko, okx, bybit, kraken, bitget, kucoin, upbit, cryptocom (alias: crypto.com → cryptocom). n8n | webhook for legacy webhook."
      },
      {
        "key": "instId",
        "value": "",
        "enabled": false,
        "description": "Venue symbol override (e.g. BTCUSDT, BTC-USDT)."
      },
      {
        "key": "bar",
        "value": "",
        "enabled": false,
        "description": "Candle interval (e.g. 1m, 1h, 4h, 1d)."
      },
      {
        "key": "limit",
        "value": "",
        "enabled": false,
        "description": "Candle count (default ~200)."
      }
    ],
    "catalogMeta": {
      "segment": "signal",
      "name": "Trading Signal",
      "summary": "AI trading signal from CEX OHLCV technical analysis",
      "description": "Generates a directional trading signal with bias, confidence, entry context, and reasoning from OHLCV candles. Use when an agent needs a te…",
      "priceUsd": "0.005",
      "category": "signals"
    }
  },
  {
    "segment": "spcx",
    "id": "x402-spcx",
    "label": "SPCX SpaceX IPO Intelligence: SpaceX IPO token (SPCXx) Nasdaq vs on-chain spread",
    "method": "GET",
    "params": [
      {
        "key": "symbol",
        "value": "SPCXx",
        "enabled": true,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "spcx",
      "name": "SPCX SpaceX IPO Intelligence",
      "summary": "SpaceX IPO token (SPCXx) Nasdaq vs on-chain spread",
      "description": "Tokenized equity intelligence for SpaceX IPO exposure (SPCXx). Use when an agent compares Nasdaq reference price vs on-chain SPCX venues fo…",
      "priceUsd": "0.02",
      "category": "analytics"
    }
  },
  {
    "segment": "equity",
    "id": "x402-equity",
    "label": "Tokenized Equity Intelligence: xStocks equity spread — Nasdaq vs on-chain (TSLAx, NVDAx, …)",
    "method": "GET",
    "params": [
      {
        "key": "symbol",
        "value": "",
        "enabled": true,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "equity",
      "name": "Tokenized Equity Intelligence",
      "summary": "xStocks equity spread — Nasdaq vs on-chain (TSLAx, NVDAx, …)",
      "description": "Parametric tokenized equity intelligence for xStocks symbols. Use when an agent needs Nasdaq vs on-chain premium/discount, venue prices, an…",
      "priceUsd": "0.02",
      "category": "analytics"
    }
  },
  {
    "segment": "indicator",
    "id": "x402-indicator",
    "label": "Technical Indicators: Combine RSI, MACD, EMA, Bollinger, and 20+ indicators in one call",
    "method": "GET",
    "params": [
      {
        "key": "symbol",
        "value": "BTCUSDT",
        "enabled": true,
        "description": ""
      },
      {
        "key": "source",
        "value": "binance",
        "enabled": false,
        "description": ""
      },
      {
        "key": "interval",
        "value": "1h",
        "enabled": false,
        "description": ""
      },
      {
        "key": "limit",
        "value": "200",
        "enabled": true,
        "description": ""
      },
      {
        "key": "series",
        "value": "false",
        "enabled": false,
        "description": ""
      },
      {
        "key": "indicators",
        "value": "rsi",
        "enabled": false,
        "description": "Comma-separated ids e.g. rsi,macd. Per-indicator params: rsi.period=21"
      }
    ],
    "catalogMeta": {
      "segment": "indicator",
      "name": "Technical Indicators",
      "summary": "Combine RSI, MACD, EMA, Bollinger, and 20+ indicators in one call",
      "description": "Computes multiple technical indicators from OHLCV candles in one agent-readable response. Use when an agent needs RSI/MACD/EMA/Bollinger (o…",
      "priceUsd": "0.005",
      "category": "analytics"
    }
  },
  {
    "segment": "sentiment",
    "id": "x402-sentiment",
    "label": "Market Sentiment: 30-day crypto sentiment scores by ticker",
    "method": "GET",
    "params": [
      {
        "key": "ticker",
        "value": "general",
        "enabled": true,
        "description": "Ticker symbol or general for broad feed."
      }
    ],
    "catalogMeta": {
      "segment": "sentiment",
      "name": "Market Sentiment",
      "summary": "30-day crypto sentiment scores by ticker",
      "description": "Daily sentiment breakdown (positive/negative/neutral/score) over ~30 days from news-derived analysis. Use when an agent gauges crowd mood o…",
      "priceUsd": "0.005",
      "category": "analytics"
    }
  },
  {
    "segment": "event",
    "id": "x402-event",
    "label": "Crypto Events: Upcoming and recent crypto events calendar",
    "method": "GET",
    "params": [
      {
        "key": "ticker",
        "value": "general",
        "enabled": true,
        "description": "Ticker symbol or general for broad feed."
      }
    ],
    "catalogMeta": {
      "segment": "event",
      "name": "Crypto Events",
      "summary": "Upcoming and recent crypto events calendar",
      "description": "Lists conferences, launches, listings, and macro events affecting crypto. Use when an agent schedules research around catalysts or filters…",
      "priceUsd": "0.005",
      "category": "news"
    }
  },
  {
    "segment": "trending-headline",
    "id": "x402-trending-headline",
    "label": "Trending Headlines: What is trending in crypto news right now",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "trending-headline",
      "name": "Trending Headlines",
      "summary": "What is trending in crypto news right now",
      "description": "Hot headlines and viral crypto stories currently moving the market. Use when an agent needs the top narrative of the day rather than a full…",
      "priceUsd": "0.005",
      "category": "news"
    }
  },
  {
    "segment": "sundown-digest",
    "id": "x402-sundown-digest",
    "label": "Sundown Digest: End-of-day crypto market recap",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "sundown-digest",
      "name": "Sundown Digest",
      "summary": "End-of-day crypto market recap",
      "description": "Daily wrap-up of key market moves, headlines, and themes. Use when an agent summarizes the session for reports or next-day planning. No req…",
      "priceUsd": "0.005",
      "category": "news"
    }
  },
  {
    "segment": "health",
    "id": "x402-health",
    "label": "API Health: Paid liveness probe for Syra API",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "health",
      "name": "API Health",
      "summary": "Paid liveness probe for Syra API",
      "description": "Minimal paid health check confirming Syra API is up and x402 settlement works. Use when an agent or monitor verifies connectivity before ba…",
      "priceUsd": "0.001",
      "category": "health"
    }
  },
  {
    "segment": "mpp/health",
    "id": "x402-mpp-health",
    "label": "MPP Health Check: Machine Payments Protocol test lane (x402 v2)",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "mpp/health",
      "name": "MPP Health Check",
      "summary": "Machine Payments Protocol test lane (x402 v2)",
      "description": "MPP-compatible health endpoint with same x402 v2 flow as /health. Use when testing Tempo/Stripe-style machine payment clients against Syra.…",
      "priceUsd": "0.001",
      "category": "health"
    }
  },
  {
    "segment": "arbitrage",
    "id": "x402-arbitrage",
    "label": "Cross-CEX Arbitrage Bundle: CMC top assets + live CEX snapshots + ranked spreads",
    "method": "GET",
    "params": [
      {
        "key": "limit",
        "value": "10",
        "enabled": true,
        "description": "Number of top tradable assets to include (default 10, max 25)."
      }
    ],
    "catalogMeta": {
      "segment": "arbitrage",
      "name": "Cross-CEX Arbitrage Bundle",
      "summary": "CMC top assets + live CEX snapshots + ranked spreads",
      "description": "Bundles CoinMarketCap-style top tradable assets (stablecoins skipped) with live cross-venue USDT spot snapshots and ranked buy/sell routes…",
      "priceUsd": "0.04",
      "category": "analytics"
    }
  },
  {
    "segment": "jupiter/quote",
    "id": "x402-jupiter-quote",
    "label": "Jupiter Swap Quote: Jupiter Swap V1 ExactIn quote with Syra referral fee",
    "method": "GET",
    "params": [
      {
        "key": "inputMint",
        "value": "",
        "enabled": true,
        "description": "Input token mint (base58)"
      },
      {
        "key": "outputMint",
        "value": "",
        "enabled": true,
        "description": "Output token mint (referral fee taken on output)"
      },
      {
        "key": "amount",
        "value": "",
        "enabled": true,
        "description": "Input amount in raw token units"
      },
      {
        "key": "slippageBps",
        "value": "50",
        "enabled": false,
        "description": ""
      },
      {
        "key": "swapMode",
        "value": "",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "jupiter/quote",
      "name": "Jupiter Swap Quote",
      "summary": "Jupiter Swap V1 ExactIn quote with Syra referral fee",
      "description": "Fetches a Jupiter Swap V1 quoteResponse for ExactIn swaps with Syra referral platform fee when configured on-chain. Use when an agent price…",
      "priceUsd": "0.001",
      "category": "defi"
    }
  },
  {
    "segment": "pumpfun/trending",
    "id": "x402-pumpfun-trending",
    "label": "pump.fun Trending: Trending pump.fun coins list",
    "method": "GET",
    "params": [
      {
        "key": "limit",
        "value": "20",
        "enabled": true,
        "description": ""
      },
      {
        "key": "offset",
        "value": "0",
        "enabled": false,
        "description": ""
      },
      {
        "key": "includeNsfw",
        "value": "false",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "pumpfun/trending",
      "name": "pump.fun Trending",
      "summary": "Trending pump.fun coins list",
      "description": "Returns trending pump.fun coins from frontend-api-v3 (falls back to top-runners when primary feed is empty). Use when an agent scans hot me…",
      "priceUsd": "0.001",
      "category": "defi"
    }
  },
  {
    "segment": "pumpfun/movers",
    "id": "x402-pumpfun-movers",
    "label": "pump.fun Movers: pump.fun market movers list",
    "method": "GET",
    "params": [
      {
        "key": "limit",
        "value": "20",
        "enabled": true,
        "description": ""
      },
      {
        "key": "offset",
        "value": "0",
        "enabled": false,
        "description": ""
      },
      {
        "key": "includeNsfw",
        "value": "false",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "pumpfun/movers",
      "name": "pump.fun Movers",
      "summary": "pump.fun market movers list",
      "description": "Returns pump.fun market movers from frontend-api-v3 (falls back to currently-live when primary is empty). Use when an agent finds coins wit…",
      "priceUsd": "0.001",
      "category": "defi"
    }
  },
  {
    "segment": "pumpfun/analyzer",
    "id": "x402-pumpfun-analyzer",
    "label": "pump.fun Memecoin Analyzer: Full memecoin due-diligence for any Solana mint",
    "method": "GET",
    "params": [
      {
        "key": "mint",
        "value": "",
        "enabled": true,
        "description": "Solana token mint (base58)"
      }
    ],
    "catalogMeta": {
      "segment": "pumpfun/analyzer",
      "name": "pump.fun Memecoin Analyzer",
      "summary": "Full memecoin due-diligence for any Solana mint",
      "description": "Deep memecoin analysis for pump.fun or graduated tokens. Use when an agent must score risk/reward before trading. Input: mint (base58). Ret…",
      "priceUsd": "0.02",
      "category": "analytics"
    }
  },
  {
    "segment": "pumpfun/scout",
    "id": "x402-pumpfun-scout",
    "label": "pump.fun Scout: Live pump.fun alpha/beta/predicted/utility scout",
    "method": "GET",
    "params": [
      {
        "key": "segment",
        "value": "alpha",
        "enabled": true,
        "description": ""
      },
      {
        "key": "period",
        "value": "today",
        "enabled": true,
        "description": ""
      },
      {
        "key": "limit",
        "value": "10",
        "enabled": true,
        "description": ""
      },
      {
        "key": "minPumpScore",
        "value": "48",
        "enabled": false,
        "description": ""
      },
      {
        "key": "llm",
        "value": "false",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "pumpfun/scout",
      "name": "pump.fun Scout",
      "summary": "Live pump.fun alpha/beta/predicted/utility scout",
      "description": "Live pump.fun intelligence with selector param segment=alpha|beta|predicted|utility. Optional period, limit, minPumpScore, llm. Returns sco…",
      "priceUsd": "0.005",
      "category": "analytics"
    }
  },
  {
    "segment": "rise",
    "id": "x402-rise",
    "label": "RISE Scout: Live RISE market intel and agent targets",
    "method": "GET",
    "params": [
      {
        "key": "view",
        "value": "intel",
        "enabled": true,
        "description": ""
      },
      {
        "key": "mint",
        "value": "",
        "enabled": false,
        "description": ""
      },
      {
        "key": "limit",
        "value": "25",
        "enabled": true,
        "description": ""
      },
      {
        "key": "tier",
        "value": "",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "rise",
      "name": "RISE Scout",
      "summary": "Live RISE market intel and agent targets",
      "description": "Live RISE intelligence with view=intel|markets|targets. Optional mint, limit, tier=ready|watch. Returns UPONLY token snapshot, fund lens, r…",
      "priceUsd": "0.005",
      "category": "analytics"
    }
  },
  {
    "segment": "coingecko",
    "id": "x402-coingecko",
    "label": "CoinGecko Scout: Live CoinGecko top gainers brief",
    "method": "GET",
    "params": [
      {
        "key": "view",
        "value": "brief",
        "enabled": true,
        "description": ""
      },
      {
        "key": "topN",
        "value": "8",
        "enabled": true,
        "description": ""
      },
      {
        "key": "minMarketCap",
        "value": "1000000",
        "enabled": false,
        "description": ""
      },
      {
        "key": "includeNews",
        "value": "true",
        "enabled": false,
        "description": ""
      },
      {
        "key": "llm",
        "value": "false",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "coingecko",
      "name": "CoinGecko Scout",
      "summary": "Live CoinGecko top gainers brief",
      "description": "Live CoinGecko scout with view=brief|gainers|predictions. Optional topN, minMarketCap, includeNews, llm. Returns top gainers, digests, pred…",
      "priceUsd": "0.001",
      "category": "analytics"
    }
  },
  {
    "segment": "dexscreener/pairs",
    "id": "x402-dexscreener-pairs",
    "label": "DexScreener Pairs: DEX pairs by chain/token or search query",
    "method": "GET",
    "params": [
      {
        "key": "chainId",
        "value": "",
        "enabled": false,
        "description": ""
      },
      {
        "key": "tokenAddress",
        "value": "",
        "enabled": false,
        "description": ""
      },
      {
        "key": "q",
        "value": "",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "dexscreener/pairs",
      "name": "DexScreener Pairs",
      "summary": "DEX pairs by chain/token or search query",
      "description": "Onchain DEX pair data from DexScreener across 80+ chains. Use when an agent needs live price, liquidity, volume, and txn counts for a token…",
      "priceUsd": "0.001",
      "category": "analytics"
    }
  },
  {
    "segment": "geckoterminal/pools",
    "id": "x402-geckoterminal-pools",
    "label": "GeckoTerminal Pools: Trending or new DEX pools on a network",
    "method": "GET",
    "params": [
      {
        "key": "network",
        "value": "solana",
        "enabled": false,
        "description": ""
      },
      {
        "key": "kind",
        "value": "trending",
        "enabled": false,
        "description": ""
      },
      {
        "key": "limit",
        "value": "20",
        "enabled": true,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "geckoterminal/pools",
      "name": "GeckoTerminal Pools",
      "summary": "Trending or new DEX pools on a network",
      "description": "Trending or newly listed DEX pools from GeckoTerminal across 100+ networks. Use when an agent scouts fresh liquidity or momentum pools on S…",
      "priceUsd": "0.001",
      "category": "defi"
    }
  },
  {
    "segment": "defillama/tvl",
    "id": "x402-defillama-tvl",
    "label": "DefiLlama TVL: Protocol or chain TVL from DefiLlama",
    "method": "GET",
    "params": [
      {
        "key": "protocol",
        "value": "",
        "enabled": false,
        "description": ""
      },
      {
        "key": "chain",
        "value": "",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "defillama/tvl",
      "name": "DefiLlama TVL",
      "summary": "Protocol or chain TVL from DefiLlama",
      "description": "Total value locked for a DeFi protocol or blockchain from DefiLlama. Use when an agent assesses protocol scale, chain dominance, or macro D…",
      "priceUsd": "0.001",
      "category": "defi"
    }
  },
  {
    "segment": "rugcheck/report",
    "id": "x402-rugcheck-report",
    "label": "RugCheck Token Report: Solana token risk report from RugCheck",
    "method": "GET",
    "params": [
      {
        "key": "mint",
        "value": "",
        "enabled": true,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "rugcheck/report",
      "name": "RugCheck Token Report",
      "summary": "Solana token risk report from RugCheck",
      "description": "Solana token risk report from RugCheck: mint/freeze authority, holder concentration, LP status, and risk score. Use when an agent screens m…",
      "priceUsd": "0.005",
      "category": "signals"
    }
  },
  {
    "segment": "pyth/price",
    "id": "x402-pyth-price",
    "label": "Pyth Oracle Prices: Real-time Pyth oracle prices via Hermes",
    "method": "GET",
    "params": [
      {
        "key": "symbols",
        "value": "",
        "enabled": true,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "pyth/price",
      "name": "Pyth Oracle Prices",
      "summary": "Real-time Pyth oracle prices via Hermes",
      "description": "Latest Pyth oracle prices from Hermes for major crypto feeds. Use when an agent needs authoritative onchain-derived spot prices (BTC, ETH,…",
      "priceUsd": "0.001",
      "category": "analytics"
    }
  },
  {
    "segment": "insights/network-health",
    "id": "x402-insights-network-health",
    "label": "Solana Network Health: Solana slot, epoch, TPS, and priority fee snapshot",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/network-health",
      "name": "Solana Network Health",
      "summary": "Solana slot, epoch, TPS, and priority fee snapshot",
      "description": "Real-time Solana mainnet health metrics: current slot, epoch progress, average TPS from recent performance samples, and median priority fee…",
      "priceUsd": "0.01",
      "category": "analytics"
    }
  },
  {
    "segment": "insights/gas-oracle",
    "id": "x402-insights-gas-oracle",
    "label": "Solana Gas Oracle: Solana priority fee percentiles for transaction inclusion",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/gas-oracle",
      "name": "Solana Gas Oracle",
      "summary": "Solana priority fee percentiles for transaction inclusion",
      "description": "Priority fee oracle derived from recent Solana mainnet samples. Returns min, p25, p50, p75, p95, and max priority fees in lamports. Use whe…",
      "priceUsd": "0.01",
      "category": "analytics"
    }
  },
  {
    "segment": "insights/market-pulse",
    "id": "x402-insights-market-pulse",
    "label": "Cross-Asset Market Pulse: SOL, BTC, ETH spot prices via Pyth oracle",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/market-pulse",
      "name": "Cross-Asset Market Pulse",
      "summary": "SOL, BTC, ETH spot prices via Pyth oracle",
      "description": "Cross-asset market pulse with latest Pyth oracle prices for SOL/USD, BTC/USD, and ETH/USD including confidence intervals and publish times.…",
      "priceUsd": "0.02",
      "category": "analytics"
    }
  },
  {
    "segment": "insights/token-metrics",
    "id": "x402-insights-token-metrics",
    "label": "Token Liquidity Metrics: SOL DEX pair metrics via DexScreener",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/token-metrics",
      "name": "Token Liquidity Metrics",
      "summary": "SOL DEX pair metrics via DexScreener",
      "description": "Token liquidity and trading metrics for SOL across major DEX pairs from DexScreener. Returns top pairs with price, 24h volume, price change…",
      "priceUsd": "0.03",
      "category": "analytics"
    }
  },
  {
    "segment": "insights/defi-tvl",
    "id": "x402-insights-defi-tvl",
    "label": "Solana DeFi TVL: Solana chain TVL overview from DefiLlama",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/defi-tvl",
      "name": "Solana DeFi TVL",
      "summary": "Solana chain TVL overview from DefiLlama",
      "description": "Solana DeFi total value locked overview from DefiLlama. Use when an agent assesses macro DeFi health and capital allocation on the Solana e…",
      "priceUsd": "0.05",
      "category": "defi"
    }
  },
  {
    "segment": "insights/volatility-index",
    "id": "x402-insights-volatility-index",
    "label": "Volatility Index: Computed volatility index from major Pyth price feeds",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/volatility-index",
      "name": "Volatility Index",
      "summary": "Computed volatility index from major Pyth price feeds",
      "description": "Volatility index computed from Pyth price feed confidence intervals across SOL, BTC, and ETH. Returns index score and per-asset uncertainty…",
      "priceUsd": "0.1",
      "category": "analytics"
    }
  },
  {
    "segment": "insights/ecosystem-brief",
    "id": "x402-insights-ecosystem-brief",
    "label": "Solana Ecosystem Brief: Premium combined network, market, and DeFi snapshot via PayAI",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "insights/ecosystem-brief",
      "name": "Solana Ecosystem Brief",
      "summary": "Premium combined network, market, and DeFi snapshot via PayAI",
      "description": "Premium PayAI-facilitated Labs endpoint combining Solana network health, cross-asset market pulse (SOL/BTC/ETH), and DeFi TVL in one respon…",
      "priceUsd": "0.05",
      "category": "analytics"
    }
  },
  {
    "segment": "assets",
    "id": "x402-assets",
    "label": "Assets Board: Tokens.xyz curated assets board with filter and sort",
    "method": "GET",
    "params": [
      {
        "key": "list",
        "value": "all",
        "enabled": true,
        "description": ""
      },
      {
        "key": "groupBy",
        "value": "asset",
        "enabled": false,
        "description": ""
      },
      {
        "key": "assetClass",
        "value": "all",
        "enabled": true,
        "description": ""
      },
      {
        "key": "q",
        "value": "",
        "enabled": false,
        "description": "Search name, symbol, ref, or assetId"
      },
      {
        "key": "sort",
        "value": "marketCap",
        "enabled": true,
        "description": ""
      },
      {
        "key": "order",
        "value": "",
        "enabled": false,
        "description": ""
      },
      {
        "key": "limit",
        "value": "20",
        "enabled": true,
        "description": ""
      },
      {
        "key": "offset",
        "value": "0",
        "enabled": false,
        "description": ""
      },
      {
        "key": "maxPages",
        "value": "20",
        "enabled": false,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "assets",
      "name": "Assets Board",
      "summary": "Tokens.xyz curated assets board with filter and sort",
      "description": "Paginated curated assets board (crypto + tokenized stocks) from Tokens.xyz — same data as the Syra Assets page. Use when an agent needs a r…",
      "priceUsd": "0.001",
      "category": "analytics"
    }
  },
  {
    "segment": "assets/detail",
    "id": "x402-assets-detail",
    "label": "Asset Detail: Tokens.xyz mint dossier for one asset",
    "method": "GET",
    "params": [
      {
        "key": "ref",
        "value": "",
        "enabled": true,
        "description": "Canonical ref e.g. btc, solana, apple (alternatives: mint, assetId, q)"
      },
      {
        "key": "mint",
        "value": "",
        "enabled": false,
        "description": "Solana mint (base58)"
      },
      {
        "key": "assetId",
        "value": "",
        "enabled": false,
        "description": "assetId e.g. bitcoin"
      },
      {
        "key": "q",
        "value": "",
        "enabled": false,
        "description": "Freeform lookup (ref, mint, or assetId)"
      }
    ],
    "catalogMeta": {
      "segment": "assets/detail",
      "name": "Asset Detail",
      "summary": "Tokens.xyz mint dossier for one asset",
      "description": "Full asset dossier: profile, risk, markets, and 1H OHLCV for a canonical asset. Use when an agent researches BTC, SOL, a stock token, or an…",
      "priceUsd": "0.005",
      "category": "analytics"
    }
  },
  {
    "segment": "bitcoin",
    "id": "x402-bitcoin",
    "label": "Bitcoin Intelligence Hub: Full Bitcoin dashboard + taker-flow bubblemap",
    "method": "GET",
    "params": [
      {
        "key": "exchange",
        "value": "binance",
        "enabled": false,
        "description": ""
      },
      {
        "key": "interval",
        "value": "1h",
        "enabled": false,
        "description": ""
      },
      {
        "key": "limit",
        "value": "200",
        "enabled": true,
        "description": ""
      }
    ],
    "catalogMeta": {
      "segment": "bitcoin",
      "name": "Bitcoin Intelligence Hub",
      "summary": "Full Bitcoin dashboard + taker-flow bubblemap",
      "description": "Complete Bitcoin intelligence bundle from the Syra BTC page. Use when an agent needs macro BTC context: price, derivatives, technicals, sen…",
      "priceUsd": "0.005",
      "category": "analytics"
    }
  },
  {
    "segment": "chat/completions",
    "id": "x402-chat-completions",
    "label": "Chat Completions (OpenRouter): OpenAI-compatible agent chat via top OpenRouter models",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "chat/completions",
      "name": "Chat Completions (OpenRouter)",
      "summary": "OpenAI-compatible agent chat via top OpenRouter models",
      "description": "OpenAI-compatible POST /chat/completions backed by 15 curated agentic OpenRouter text models. Use when an agent needs LLM reasoning, tool c…",
      "priceUsd": "0.004",
      "category": "ai"
    }
  },
  {
    "segment": "images/generations",
    "id": "x402-images-generations",
    "label": "Image Generations (OpenRouter): Text-to-image via OpenRouter Unified Image API",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "images/generations",
      "name": "Image Generations (OpenRouter)",
      "summary": "Text-to-image via OpenRouter Unified Image API",
      "description": "Paid POST /images/generations using OpenRouter Unified Image API (POST /api/v1/images). Use when an agent needs to generate marketing asset…",
      "priceUsd": "0.02",
      "category": "ai"
    }
  },
  {
    "segment": "videos/generations",
    "id": "x402-videos-generations",
    "label": "Video Generations (OpenRouter): Async text-to-video submit via OpenRouter Video API",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "videos/generations",
      "name": "Video Generations (OpenRouter)",
      "summary": "Async text-to-video submit via OpenRouter Video API",
      "description": "Paid POST /videos/generations submits an async OpenRouter video job (POST /api/v1/videos). Use when an agent needs short-form video clips f…",
      "priceUsd": "0.1",
      "category": "ai"
    }
  },
  {
    "segment": "embeddings",
    "id": "x402-embeddings",
    "label": "Embeddings (OpenRouter): Text embeddings via OpenRouter",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "embeddings",
      "name": "Embeddings (OpenRouter)",
      "summary": "Text embeddings via OpenRouter",
      "description": "Paid POST /embeddings for vector embeddings from curated OpenRouter embedding models. Use when an agent needs semantic search, clustering,…",
      "priceUsd": "0.001",
      "category": "ai"
    }
  },
  {
    "segment": "rerank",
    "id": "x402-rerank",
    "label": "Rerank (OpenRouter): Document reranking via OpenRouter",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "rerank",
      "name": "Rerank (OpenRouter)",
      "summary": "Document reranking via OpenRouter",
      "description": "Paid POST /rerank ranks candidate documents against a query using curated OpenRouter rerank models. Use when an agent needs relevance scori…",
      "priceUsd": "0.002",
      "category": "ai"
    }
  },
  {
    "segment": "audio/speech",
    "id": "x402-audio-speech",
    "label": "Text-to-Speech (OpenRouter): TTS via OpenRouter /audio/speech",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "audio/speech",
      "name": "Text-to-Speech (OpenRouter)",
      "summary": "TTS via OpenRouter /audio/speech",
      "description": "Paid POST /audio/speech synthesizes speech from text via curated OpenRouter TTS models (Kokoro, Voxtral, MAI, Gemini). Use when an agent ne…",
      "priceUsd": "0.005",
      "category": "ai"
    }
  },
  {
    "segment": "audio/transcriptions",
    "id": "x402-audio-transcriptions",
    "label": "Speech Transcription (OpenRouter): STT via OpenRouter /audio/transcriptions",
    "method": "POST",
    "params": [],
    "catalogMeta": {
      "segment": "audio/transcriptions",
      "name": "Speech Transcription (OpenRouter)",
      "summary": "STT via OpenRouter /audio/transcriptions",
      "description": "Paid POST /audio/transcriptions for speech-to-text via curated OpenRouter STT models (Whisper / GPT-4o Transcribe). Use when an agent needs…",
      "priceUsd": "0.01",
      "category": "ai"
    }
  },
  {
    "segment": "8004/stats",
    "id": "x402-8004-stats",
    "label": "8004 Global Stats: Solana 8004 agent registry aggregate statistics",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "8004/stats",
      "name": "8004 Global Stats",
      "summary": "Solana 8004 agent registry aggregate statistics",
      "description": "Global stats for the Solana 8004 trustless agent registry: total agents, feedback counts, trust tiers. Use when an agent surveys the Syra/8…",
      "priceUsd": "0.012",
      "category": "agents"
    }
  },
  {
    "segment": "8004/leaderboard",
    "id": "x402-8004-leaderboard",
    "label": "8004 Leaderboard: Top 8004 agents ranked by trust tier",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "8004/leaderboard",
      "name": "8004 Leaderboard",
      "summary": "Top 8004 agents ranked by trust tier",
      "description": "Leaderboard of registered 8004 agents sorted by trust/reputation. Use when an agent picks high-trust counterparts or benchmarks agent quali…",
      "priceUsd": "0.012",
      "category": "agents"
    }
  },
  {
    "segment": "8004/agents/search",
    "id": "x402-8004-agents-search",
    "label": "8004 Agent Search: Search Solana 8004 agents by owner or collection",
    "method": "GET",
    "params": [],
    "catalogMeta": {
      "segment": "8004/agents/search",
      "name": "8004 Agent Search",
      "summary": "Search Solana 8004 agents by owner or collection",
      "description": "Search the 8004 agent index by owner wallet, creator, or collection pointer. Use when an agent discovers agents to hire, verify, or compose…",
      "priceUsd": "0.012",
      "category": "agents"
    }
  }
];
