/** Photo template batch 3 — third style variant per context (75-library tier) */
export const POST_PHOTO_LAYOUTS_BATCH3 = [
  "photo-cover-aurora",
  "photo-cover-whisper",
  "photo-cover-prism",
  "photo-cover-vault",
  "photo-statement-beam",
  "photo-statement-neon",
  "photo-statement-lattice",
  "photo-statement-serif",
  "photo-statement-kinetic",
  "photo-quote-gilded",
  "photo-hero-tiered",
  "photo-hero-frost",
  "photo-stat-monolith",
  "photo-stat-facet",
  "photo-stat-gradient-bar",
  "photo-stat-halo",
  "photo-stat-podium",
  "photo-cards-glass-duo",
  "photo-cards-glass-quad",
  "photo-cards-marquee",
  "photo-flow-rail",
  "photo-flow-conduit",
  "photo-flow-ledger",
  "photo-compare-gradient",
  "photo-compare-slide",
] as const;

export type PostPhotoLayoutTemplateBatch3 = (typeof POST_PHOTO_LAYOUTS_BATCH3)[number];

export const POST_PHOTO_LAYOUT_LABELS_BATCH3: Record<PostPhotoLayoutTemplateBatch3, string> = {
  "photo-cover-aurora": "Cover aurora glow",
  "photo-cover-whisper": "Cover whisper minimal",
  "photo-cover-prism": "Cover prism split",
  "photo-cover-vault": "Cover vault brand",
  "photo-statement-beam": "Statement light beam",
  "photo-statement-neon": "Statement neon rail",
  "photo-statement-lattice": "Statement lattice panel",
  "photo-statement-serif": "Statement editorial serif",
  "photo-statement-kinetic": "Statement kinetic stack",
  "photo-quote-gilded": "Quote gilded frame",
  "photo-hero-tiered": "Hero tiered checklist",
  "photo-hero-frost": "Hero frost split",
  "photo-stat-monolith": "Stat monolith hero",
  "photo-stat-facet": "Stat facet prism",
  "photo-stat-gradient-bar": "Stat gradient bar",
  "photo-stat-halo": "Stat halo ring",
  "photo-stat-podium": "Stat podium stage",
  "photo-cards-glass-duo": "Cards glass duo",
  "photo-cards-glass-quad": "Cards glass quad",
  "photo-cards-marquee": "Cards marquee spotlight",
  "photo-flow-rail": "Flow vertical rail",
  "photo-flow-conduit": "Flow conduit pipeline",
  "photo-flow-ledger": "Flow ledger steps",
  "photo-compare-gradient": "Compare gradient shift",
  "photo-compare-slide": "Compare slide panels",
};
