/** Photo template batch 2 — brings library to 50+ layouts */
export const POST_PHOTO_LAYOUTS_BATCH2 = [
  "photo-cover-gradient",
  "photo-cover-eyebrow-stack",
  "photo-cover-diagonal",
  "photo-cover-type-hero",
  "photo-statement-underline",
  "photo-statement-inverted",
  "photo-statement-narrow",
  "photo-statement-gold-frame",
  "photo-statement-kicker-bottom",
  "photo-quote-centered",
  "photo-hero-numbered",
  "photo-hero-masonry",
  "photo-hero-quote",
  "photo-stat-counter-row",
  "photo-stat-narrative-first",
  "photo-stat-orbit",
  "photo-cards-stack",
  "photo-cards-bento",
  "photo-cards-spotlight",
  "photo-flow-zigzag",
  "photo-flow-arrow-chain",
  "photo-items-grid",
  "photo-closing-banner",
  "photo-closing-split",
  "photo-editorial",
] as const;

export type PostPhotoLayoutTemplateBatch2 = (typeof POST_PHOTO_LAYOUTS_BATCH2)[number];

export const POST_PHOTO_LAYOUT_LABELS_BATCH2: Record<PostPhotoLayoutTemplateBatch2, string> = {
  "photo-cover-gradient": "Cover gradient glow",
  "photo-cover-eyebrow-stack": "Cover eyebrow stack",
  "photo-cover-diagonal": "Cover diagonal split",
  "photo-cover-type-hero": "Cover hero type",
  "photo-statement-underline": "Statement underline",
  "photo-statement-inverted": "Statement inverted panel",
  "photo-statement-narrow": "Statement narrow column",
  "photo-statement-gold-frame": "Statement gold frame",
  "photo-statement-kicker-bottom": "Statement kicker bottom",
  "photo-quote-centered": "Quote centered",
  "photo-hero-numbered": "Hero numbered cards",
  "photo-hero-masonry": "Hero masonry grid",
  "photo-hero-quote": "Hero quote body",
  "photo-stat-counter-row": "Stat counter row",
  "photo-stat-narrative-first": "Stat narrative first",
  "photo-stat-orbit": "Stat orbit ring",
  "photo-cards-stack": "Cards vertical stack",
  "photo-cards-bento": "Cards bento grid",
  "photo-cards-spotlight": "Cards spotlight one",
  "photo-flow-zigzag": "Flow zigzag steps",
  "photo-flow-arrow-chain": "Flow arrow chain",
  "photo-items-grid": "Items feature grid",
  "photo-closing-banner": "Closing gold banner",
  "photo-closing-split": "Closing split CTA",
  "photo-editorial": "Editorial magazine",
};
