/** Additional layout template IDs (batch 2). Appended in layouts.ts */
export const POST_SLIDE_LAYOUTS_EXTENDED = [
  "cover-brand-lockup",
  "cover-tagline-stack",
  "cover-hero-type",
  "statement-boxed",
  "statement-kicker-bottom",
  "statement-highlight-line",
  "statement-narrow-column",
  "hero-masonry",
  "hero-numbered-cards",
  "hero-quote-body",
  "flow-zigzag",
  "flow-arrow-chain",
  "flow-compact-row",
  "cards-stack",
  "cards-mosaic",
  "cards-spotlight-one",
  "surfaces-compact-grid",
  "surfaces-featured-one",
  "surfaces-orbit",
  "impact-counter-row",
  "impact-narrative-first",
  "impact-duo",
  "closing-split-cta",
  "closing-stack-links",
  "closing-banner",
] as const;

export type PostSlideLayoutTemplateExtended = (typeof POST_SLIDE_LAYOUTS_EXTENDED)[number];

export const POST_LAYOUT_LABELS_EXTENDED: Record<PostSlideLayoutTemplateExtended, string> = {
  "cover-brand-lockup": "Cover brand lockup",
  "cover-tagline-stack": "Cover tagline stack",
  "cover-hero-type": "Cover hero type",
  "statement-boxed": "Statement boxed",
  "statement-kicker-bottom": "Statement kicker bottom",
  "statement-highlight-line": "Statement highlight",
  "statement-narrow-column": "Statement narrow",
  "hero-masonry": "Hero masonry",
  "hero-numbered-cards": "Hero numbered cards",
  "hero-quote-body": "Hero quote body",
  "flow-zigzag": "Flow zigzag",
  "flow-arrow-chain": "Flow arrow chain",
  "flow-compact-row": "Flow compact row",
  "cards-stack": "Cards stack",
  "cards-mosaic": "Cards mosaic",
  "cards-spotlight-one": "Cards spotlight",
  "surfaces-compact-grid": "Surface compact grid",
  "surfaces-featured-one": "Surface featured",
  "surfaces-orbit": "Surface orbit",
  "impact-counter-row": "Impact counter row",
  "impact-narrative-first": "Impact narrative first",
  "impact-duo": "Impact duo",
  "closing-split-cta": "Closing split CTA",
  "closing-stack-links": "Closing stack links",
  "closing-banner": "Closing banner",
};

export const POST_LAYOUT_KIND_EXTENDED: Record<PostSlideLayoutTemplateExtended, string> = {
  "cover-brand-lockup": "cover",
  "cover-tagline-stack": "cover",
  "cover-hero-type": "cover",
  "statement-boxed": "statement",
  "statement-kicker-bottom": "statement",
  "statement-highlight-line": "statement",
  "statement-narrow-column": "statement",
  "hero-masonry": "hero",
  "hero-numbered-cards": "hero",
  "hero-quote-body": "hero",
  "flow-zigzag": "flow",
  "flow-arrow-chain": "flow",
  "flow-compact-row": "flow",
  "cards-stack": "cards",
  "cards-mosaic": "cards",
  "cards-spotlight-one": "cards",
  "surfaces-compact-grid": "surfaces",
  "surfaces-featured-one": "surfaces",
  "surfaces-orbit": "surfaces",
  "impact-counter-row": "impact",
  "impact-narrative-first": "impact",
  "impact-duo": "impact",
  "closing-split-cta": "closing",
  "closing-stack-links": "closing",
  "closing-banner": "closing",
};
