/**
 * Multi-token opportunity hunters: each agent scans a watchlist each cycle and opens
 * the single best spot-long setup (by confidence, risk/reward, or composite score).
 */
export const EXPERIMENT_OPPORTUNITY_MODES = Object.freeze([
  "best_confidence",
  "best_risk_reward",
  "best_composite",
]);

/** Display token for UI filters; actual entries use the picked asset per run. */
export const MULTI_TOKEN_DISPLAY_SLUG = "multi";

export const MULTI_TOKEN_MAJORS = Object.freeze([
  "bitcoin",
  "ethereum",
  "solana",
  "bnb",
  "xrp",
]);

export const MULTI_TOKEN_LARGE_CAPS = Object.freeze([
  ...MULTI_TOKEN_MAJORS,
  "cardano",
  "dogecoin",
  "chainlink",
  "avalanche",
  "polygon",
  "polkadot",
  "litecoin",
]);

export const MULTI_TOKEN_FULL_LAB = Object.freeze([
  ...MULTI_TOKEN_LARGE_CAPS,
  "shib",
]);

/** @param {unknown} strat */
export function isMultiTokenStrategy(strat) {
  return Array.isArray(strat?.tokens) && strat.tokens.length > 0;
}

export const TRADING_EXPERIMENT_STRATEGIES_MULTI_TOKEN = Object.freeze([
  {
    id: 0,
    name: "Major hunter 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "1h",
    limit: 220,
    lookAheadBars: 48,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 1,
    name: "Large-cap scout 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "1h",
    limit: 200,
    lookAheadBars: 52,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 2,
    name: "Full universe 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_FULL_LAB],
    bar: "1h",
    limit: 200,
    lookAheadBars: 48,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "LOW" },
  },
  {
    id: 3,
    name: "Major sniper 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "1h",
    limit: 240,
    lookAheadBars: 40,
    opportunityMode: "best_confidence",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "HIGH" },
  },
  {
    id: 4,
    name: "Large-cap sniper 4h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "4h",
    limit: 200,
    lookAheadBars: 28,
    opportunityMode: "best_confidence",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "HIGH" },
  },
  {
    id: 5,
    name: "RR major 30m",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "30m",
    limit: 220,
    lookAheadBars: 72,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 6,
    name: "RR large-cap 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "1h",
    limit: 200,
    lookAheadBars: 48,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 7,
    name: "Momentum 15m majors",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "15m",
    limit: 260,
    lookAheadBars: 120,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "LOW" },
    indicatorFilter: { macd: "BULL_HIST" },
  },
  {
    id: 8,
    name: "Momentum 15m wide",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "15m",
    limit: 240,
    lookAheadBars: 140,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    indicatorFilter: { rsiBand: { max: 48 }, macd: "BULL_HIST" },
  },
  {
    id: 9,
    name: "Swing 2h wide",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "2h",
    limit: 180,
    lookAheadBars: 36,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 10,
    name: "Scout 30m full",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_FULL_LAB],
    bar: "30m",
    limit: 200,
    lookAheadBars: 80,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "LOW" },
  },
  {
    id: 11,
    name: "High conf 15m full",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_FULL_LAB],
    bar: "15m",
    limit: 280,
    lookAheadBars: 100,
    opportunityMode: "best_confidence",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "HIGH" },
  },
  {
    id: 12,
    name: "BNB+alts 1h composite",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: ["bnb", "solana", "xrp", "cardano", "dogecoin", "chainlink", "avalanche"],
    bar: "1h",
    limit: 200,
    lookAheadBars: 50,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 13,
    name: "BTC ETH SOL 4h RR",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: ["bitcoin", "ethereum", "solana"],
    bar: "4h",
    limit: 200,
    lookAheadBars: 24,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM" },
  },
  {
    id: 14,
    name: "Fast 5m majors",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "5m",
    limit: 300,
    lookAheadBars: 110,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "LOW" },
  },
]);
