/**
 * Multi-token opportunity hunters: each agent scans a watchlist each cycle and opens
 * the single best spot-long setup (by confidence, risk/reward, or composite score).
 */
export const EXPERIMENT_OPPORTUNITY_MODES = Object.freeze([
  "best_confidence",
  "best_risk_reward",
  "best_composite",
]);

/** Display token for UI filters; actual entries use the picked asset per run. */
export const MULTI_TOKEN_DISPLAY_SLUG = "multi";

export const MULTI_TOKEN_MAJORS = Object.freeze([
  "bitcoin",
  "ethereum",
  "solana",
  "bnb",
  "xrp",
]);

export const MULTI_TOKEN_LARGE_CAPS = Object.freeze([
  ...MULTI_TOKEN_MAJORS,
  "cardano",
  "dogecoin",
  "chainlink",
  "avalanche",
  "polygon",
  "polkadot",
  "litecoin",
]);

export const MULTI_TOKEN_FULL_LAB = Object.freeze([
  ...MULTI_TOKEN_LARGE_CAPS,
  "shib",
]);

/** @param {unknown} strat */
export function isMultiTokenStrategy(strat) {
  return Array.isArray(strat?.tokens) && strat.tokens.length > 0;
}

const HUNTER_GATE = Object.freeze({
  minConfidence: "MEDIUM",
  minRiskReward: 2,
  minAdx: 18,
  requireTrendMomentumAlign: true,
});

const SNIPER_GATE = Object.freeze({
  minConfidence: "HIGH",
  minRiskReward: 2.2,
  minAdx: 22,
  requireTrendMomentumAlign: true,
});

export const TRADING_EXPERIMENT_STRATEGIES_MULTI_TOKEN = Object.freeze([
  {
    id: 0,
    name: "Major hunter 4h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "4h",
    limit: 220,
    lookAheadBars: 36,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { ...SNIPER_GATE },
  },
  {
    id: 1,
    name: "Large-cap scout 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "1h",
    limit: 200,
    lookAheadBars: 52,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { ...HUNTER_GATE },
    indicatorFilter: { macd: "BULL_HIST" },
  },
  {
    id: 2,
    name: "Full universe 2h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_FULL_LAB],
    bar: "2h",
    limit: 200,
    lookAheadBars: 44,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { ...HUNTER_GATE },
  },
  {
    id: 3,
    name: "Major sniper 4h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "4h",
    limit: 240,
    lookAheadBars: 32,
    opportunityMode: "best_confidence",
    maxOpenPositions: 1,
    experimentGate: { ...SNIPER_GATE },
    indicatorFilter: { adxDiStack: "BULL" },
  },
  {
    id: 4,
    name: "Large-cap sniper 4h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "4h",
    limit: 200,
    lookAheadBars: 28,
    opportunityMode: "best_confidence",
    maxOpenPositions: 1,
    experimentGate: { ...SNIPER_GATE },
  },
  {
    id: 5,
    name: "RR major 1h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "1h",
    limit: 220,
    lookAheadBars: 56,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "MEDIUM", minRiskReward: 2.5, minAdx: 20 },
  },
  {
    id: 6,
    name: "RR large-cap 2h",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "2h",
    limit: 200,
    lookAheadBars: 40,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { ...HUNTER_GATE },
  },
  {
    id: 7,
    name: "Momentum 30m majors",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "30m",
    limit: 260,
    lookAheadBars: 100,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "HIGH", minRiskReward: 2, minAdx: 22 },
    indicatorFilter: { macd: "BULL_HIST" },
  },
  {
    id: 8,
    name: "Momentum 1h wide",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "1h",
    limit: 240,
    lookAheadBars: 54,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { ...HUNTER_GATE },
    indicatorFilter: { rsiBand: { min: 40, max: 65 }, macd: "BULL_HIST" },
  },
  {
    id: 9,
    name: "Swing 4h wide",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_LARGE_CAPS],
    bar: "4h",
    limit: 180,
    lookAheadBars: 30,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { ...SNIPER_GATE },
  },
  {
    id: 10,
    name: "Scout 1h full",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_FULL_LAB],
    bar: "1h",
    limit: 200,
    lookAheadBars: 50,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { ...HUNTER_GATE },
  },
  {
    id: 11,
    name: "High conf 30m full",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_FULL_LAB],
    bar: "30m",
    limit: 280,
    lookAheadBars: 96,
    opportunityMode: "best_confidence",
    maxOpenPositions: 1,
    experimentGate: { ...SNIPER_GATE },
  },
  {
    id: 12,
    name: "BNB+alts 2h composite",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: ["bnb", "solana", "xrp", "cardano", "dogecoin", "chainlink", "avalanche"],
    bar: "2h",
    limit: 200,
    lookAheadBars: 42,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { ...HUNTER_GATE },
    indicatorFilter: { emaStack: "GOLDEN" },
  },
  {
    id: 13,
    name: "BTC ETH SOL 4h RR",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: ["bitcoin", "ethereum", "solana"],
    bar: "4h",
    limit: 200,
    lookAheadBars: 28,
    opportunityMode: "best_risk_reward",
    maxOpenPositions: 1,
    experimentGate: { ...SNIPER_GATE },
  },
  {
    id: 14,
    name: "Fast 15m majors",
    token: MULTI_TOKEN_DISPLAY_SLUG,
    tokens: [...MULTI_TOKEN_MAJORS],
    bar: "15m",
    limit: 300,
    lookAheadBars: 120,
    opportunityMode: "best_composite",
    maxOpenPositions: 1,
    experimentGate: { minConfidence: "HIGH", minRiskReward: 2.2, minAdx: 24 },
    indicatorFilter: { macd: "BULL_HIST", adxDiStack: "BULL" },
  },
]);
