/**
 * Resource path segments for GET /.well-known/x402 (no leading slash).
 * Keep in sync with actual x402 mounts in index.js.
 */
export const X402_DISCOVERY_RESOURCE_PATHS = [
  // Core
  "brain",
  "news",
  "signal",
  "sentiment",
  "event",
  "trending-headline",
  "sundown-digest",
  "check-status",
  "mpp/v1/check-status",
  // Search & automation
  "exa-search",
  "browser-use",
  // Partner: Nansen, DexScreener, Jupiter, Rugcheck, Bubblemaps
  "smart-money",
  "dexscreener",
  "token-god-mode",
  "trending-jupiter",
  "jupiter/swap/order",
  "squid/route",
  "squid/status",
  "token-report",
  "token-statistic",
  "token-risk/alerts",
  "bubblemaps/maps",
  // Binance & CoinGecko
  "binance/correlation",
  "binance/correlation-matrix",
  "binance/spot/ticker/24hr",
  "binance/spot/depth",
  "binance/spot/exchange-info",
  "binance/spot/account",
  "binance/spot/order",
  "coingecko/simple-price",
  "coingecko/onchain/token-price",
  "coingecko/onchain/search-pools",
  "coingecko/onchain/trending-pools",
  "coingecko/onchain/token",
  // CoinMarketCap x402
  "coinmarketcap",
  // Kraken market
  "kraken/ticker",
  "kraken/orderbook",
  "kraken/ohlc",
  "kraken/trades",
  "kraken/status",
  "kraken/server-time",
  // KuCoin spot
  "kucoin/ticker",
  "kucoin/stats",
  "kucoin/orderbook",
  "kucoin/trades",
  "kucoin/candles",
  "kucoin/symbols",
  "kucoin/currencies",
  "kucoin/server-time",
  // OKX market
  "okx/ticker",
  "okx/tickers",
  "okx/books",
  "okx/candles",
  "okx/history-candles",
  "okx/trades",
  "okx/history-trades",
  "okx/index-tickers",
  "okx/funding-rate",
  "okx/funding-rate-history",
  "okx/open-interest",
  "okx/history-open-interest",
  "okx/mark-price",
  "okx/instruments",
  "okx/time",
  // OKX DEX
  "okx/dex/price",
  "okx/dex/prices",
  "okx/dex/kline",
  "okx/dex/trades",
  "okx/dex/index",
  "okx/dex/signal-chains",
  "okx/dex/signal-list",
  "okx/dex/memepump-chains",
  "okx/dex/memepump-tokens",
  "okx/dex/memepump-token-details",
  "okx/dex/memepump-token-dev-info",
  "okx/dex/memepump-similar-tokens",
  "okx/dex/memepump-token-bundle-info",
  "okx/dex/memepump-aped-wallet",
  // Giza
  "giza/protocols",
  "giza/agent",
  "giza/portfolio",
  "giza/apr",
  "giza/performance",
  "giza/activate",
  "giza/withdraw",
  "giza/top-up",
  "giza/update-protocols",
  "giza/run",
  // Messari
  "messari/ai",
  "messari/assets",
  "messari/assets/details",
  "messari/assets/metrics",
  "messari/ath",
  "messari/roi",
  "messari/timeseries",
  "messari/signal",
  "messari/signal/timeseries",
  "messari/mindshare-gainers",
  "messari/mindshare-losers",
  "messari/news",
  "messari/token-unlocks",
  "messari/token-unlocks/assets",
  "messari/token-unlocks/allocations",
  "messari/token-unlocks/vesting",
  "messari/fundraising",
  "messari/fundraising/investors",
  "messari/fundraising/projects",
  "messari/fundraising/mna",
  "messari/stablecoins",
  "messari/networks",
  "messari/x-users",
  "messari/x-users/timeseries",
  // Analytics
  "analytics/summary",
  // 8004
  "8004",
  "8004scan",
  "heylol",
  "x",
  "quicknode/balance",
  "quicknode/transaction",
  "quicknode/rpc",
  "bankr/balances",
  "bankr/prompt",
  "bankr/job",
  "bankr/job/cancel",
  "neynar/user",
  "neynar/feed",
  "neynar/cast",
  "neynar/search",
  "siwa/nonce",
  "siwa/verify",
  "erc8004",
];
