/** Slide layout batch 3 — brings video library to 50+ templates */
export const POST_SLIDE_LAYOUTS_BATCH3 = [
  "cover-gradient-ring",
  "cover-ship-stamp",
  "cover-corner-logo",
  "cover-dual-badge",
  "statement-inverted-panel",
  "statement-gold-frame",
  "statement-split-highlight",
  "hero-pillar-trio",
  "hero-highlight-cards",
  "hero-stacked-quote",
  "flow-vertical-rail",
  "flow-step-cards",
  "flow-ladder",
  "cards-glass-row",
  "cards-featured-trio",
  "cards-accent-strip",
  "surfaces-icon-row",
  "surfaces-diamond-grid",
  "impact-orbit-stats",
  "impact-spotlight-narrative",
  "impact-mega-stat",
  "closing-gold-banner",
  "closing-minimal-type",
  "pillars-compact",
  "metric-ribbon",
] as const;

export type PostSlideLayoutTemplateBatch3 = (typeof POST_SLIDE_LAYOUTS_BATCH3)[number];

export const POST_LAYOUT_LABELS_BATCH3: Record<PostSlideLayoutTemplateBatch3, string> = {
  "cover-gradient-ring": "Cover gradient ring",
  "cover-ship-stamp": "Cover ship stamp",
  "cover-corner-logo": "Cover corner logo",
  "cover-dual-badge": "Cover dual badge",
  "statement-inverted-panel": "Statement inverted",
  "statement-gold-frame": "Statement gold frame",
  "statement-split-highlight": "Statement split highlight",
  "hero-pillar-trio": "Hero pillar trio",
  "hero-highlight-cards": "Hero highlight cards",
  "hero-stacked-quote": "Hero stacked quote",
  "flow-vertical-rail": "Flow vertical rail",
  "flow-step-cards": "Flow step cards",
  "flow-ladder": "Flow ladder",
  "cards-glass-row": "Cards glass row",
  "cards-featured-trio": "Cards featured trio",
  "cards-accent-strip": "Cards accent strip",
  "surfaces-icon-row": "Surface icon row",
  "surfaces-diamond-grid": "Surface diamond grid",
  "impact-orbit-stats": "Impact orbit stats",
  "impact-spotlight-narrative": "Impact spotlight narrative",
  "impact-mega-stat": "Impact mega stat",
  "closing-gold-banner": "Closing gold banner",
  "closing-minimal-type": "Closing minimal type",
  "pillars-compact": "Pillars compact",
  "metric-ribbon": "Metric ribbon",
};

export const POST_LAYOUT_KIND_BATCH3: Record<PostSlideLayoutTemplateBatch3, string> = {
  "cover-gradient-ring": "cover",
  "cover-ship-stamp": "cover",
  "cover-corner-logo": "cover",
  "cover-dual-badge": "cover",
  "statement-inverted-panel": "statement",
  "statement-gold-frame": "statement",
  "statement-split-highlight": "statement",
  "hero-pillar-trio": "hero",
  "hero-highlight-cards": "hero",
  "hero-stacked-quote": "hero",
  "flow-vertical-rail": "flow",
  "flow-step-cards": "flow",
  "flow-ladder": "flow",
  "cards-glass-row": "cards",
  "cards-featured-trio": "cards",
  "cards-accent-strip": "cards",
  "surfaces-icon-row": "surfaces",
  "surfaces-diamond-grid": "surfaces",
  "impact-orbit-stats": "impact",
  "impact-spotlight-narrative": "impact",
  "impact-mega-stat": "impact",
  "closing-gold-banner": "closing",
  "closing-minimal-type": "closing",
  "pillars-compact": "hero",
  "metric-ribbon": "impact",
};
